name: CI - Visualyzer

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: ./src/api

jobs:
  ci-api:
    name: CI - Visualyzer API

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src/api

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Checkout code to run against Node.js version ${{ matrix.node-version }}
        uses: actions/checkout@v2
      - name: Setup Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install the project with a clean slate
        run: npm ci
      - name: Run npm build if present
        run: npm run build --if-present
      - name: Run the tests
        run: npm test

  ci-web:
    name: CI - Visualyzer Web

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src/web

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Checkout code to run against Node.js version ${{ matrix.node-version }}
        uses: actions/checkout@v2
      - name: Setup Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install the project with a clean slate
        run: npm ci
      - name: Run npm build if present
        run: npm run build --if-present
      - name: Run the tests
        run: npm test
