name: CI -Visualyzer Web

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: ./src/web

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Checkout code from ${{ matrix.node-version }}
        uses: actions/checkout@v2
      - name: Setup Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install the project with a clean slate
        run: npm ci
      - name: Run npm build if present
        run: npm run build --if-present
      - name: Run the tests (Pass if not tests are found)
        run: npm test --passWithNoTests
