name: CD - Visualyzer

on:
  release:
    types: [created]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: "visualyzer"
  PATH_DEPLOY: "./wwwroot"
  PATH_API: "./src/api"
  PATH_WEB: "./src/web"
  NODE_VERSION: "14.x"

jobs:
  cd-api-web:
    name: Deploy - Visualyzer App

    runs-on: ubuntu-latest

    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js version ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install API dependencies
        working-directory: ${{ env.PATH_API }}
        run: npm ci
      - name: Run API test & build
        working-directory: ${{ env.PATH_API }}
        run: |
          npm run test
          npm run build
      - name: Install Web dependencies
        working-directory: ${{ env.PATH_WEB }}
        run: npm ci
      - name: Run Web test & build
        working-directory: ${{ env.PATH_WEB }}
        run: |
          npm run test
          npm run build
      - name: "Deploy to Azure WebApp"
        working-directory: ${{ env.PATH_DEPLOY }}
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_NAME }}
