name: CI - Visualyzer

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PATH_API: "./src/api"
  PATH_WEB: "./src/web"
  NODE_VERSION: "14.x"

jobs:
  ci-api:
    name: CI - Visualyzer API

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.PATH_API }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js version ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm ci
      - name: Run build and test (if present)
        run: |
          npm run build:ci --if-present
          npm run test:ci --if-present

  ci-web:
    name: CI - Visualyzer Web

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.PATH_WEB }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js version ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm ci
      - name: Run build and test (if present)
        run: |
          npm run build:ci --if-present
          npm run test:ci --if-present
