name: CI - Visualyzer

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  AZURE_APP_PACKAGE_PATH_API: "./src/api"
  AZURE_APP_PACKAGE_PATH_WEB: "./src/web"
  NODE_VERSION: "14.x"

jobs:
  ci-api:
    name: CI - Visualyzer API

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.AZURE_APP_PACKAGE_PATH_API }}

    steps:
      - name: Checkout code ${{ env.GITHUB_WORKSPACE }}
        uses: actions/checkout@v2
      - name: Setup Node.js version ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install the project with a clean slate (npm ci)
        run: npm ci
      - name: Run npm build if present
        run: npm run build --if-present
      - name: Run the tests if present
        run: npm test --if-present

  ci-web:
    name: CI - Visualyzer Web

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.AZURE_APP_PACKAGE_PATH_WEB }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js version ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install the project with a clean slate (npm ci)
        run: npm ci
      - name: Run npm build if present
        run: npm run build --if-present
      - name: Run the tests if present
        run: npm test --if-present
