name: CI - Visualyzer

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  API_PATH: "./src/api"
  WEB_PATH: "./src/web"
  NODE_VERSION: "14.x"

jobs:
  ci-api-web:
    name: CI - Visualyzer

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js version ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: API - Install the dependencies (npm ci)
        working-directory: ${{ env.API_PATH }}
        run: npm ci
      - name: API - Run build if present
        working-directory: ${{ env.API_PATH }}
        run: npm run build --if-present
      - name: API - Run tests if present
        working-directory: ${{ env.API_PATH }}
        run: npm test --if-present
      - name: WEB - Install the dependencies (npm ci)
        working-directory: ${{ env.WEB_PATH }}
        run: npm ci
      - name: WEB - Run build if present
        working-directory: ${{ env.WEB_PATH }}
        run: npm run build --if-present
      - name: WEB - Run tests if present
        working-directory: ${{ env.WEB_PATH }}
        run: npm test --if-present
